/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stark.industries;

import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.*;


/**
 *
 * @author DarkGamerX100
 */
public class Stark_Industries_Visitor extends javax.swing.JFrame {

    /**
     * Creates new form Stark_Industries_Visitor
     */
    public Stark_Industries_Visitor() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_Hardware = new javax.swing.JButton();
        btn_Software = new javax.swing.JButton();
        btn_Accessories = new javax.swing.JButton();
        btn_AboutUs = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("www.starkindustries.org");

        jPanel2.setLayout(null);

        btn_Hardware.setBackground(new java.awt.Color(0, 102, 102));
        btn_Hardware.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        btn_Hardware.setForeground(new java.awt.Color(51, 204, 0));
        btn_Hardware.setText("HARDWARE");
        btn_Hardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HardwareActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Hardware);
        btn_Hardware.setBounds(10, 60, 210, 60);

        btn_Software.setBackground(new java.awt.Color(4, 88, 88));
        btn_Software.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btn_Software.setForeground(new java.awt.Color(51, 204, 0));
        btn_Software.setText("SOFTWARE");
        btn_Software.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SoftwareActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Software);
        btn_Software.setBounds(280, 60, 210, 60);

        btn_Accessories.setBackground(new java.awt.Color(0, 102, 102));
        btn_Accessories.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btn_Accessories.setForeground(new java.awt.Color(51, 204, 0));
        btn_Accessories.setText("ACCESSORIES");
        btn_Accessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccessoriesActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Accessories);
        btn_Accessories.setBounds(570, 60, 230, 60);

        btn_AboutUs.setBackground(new java.awt.Color(0, 102, 102));
        btn_AboutUs.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btn_AboutUs.setForeground(new java.awt.Color(51, 204, 0));
        btn_AboutUs.setText("ABOUT US");
        jPanel2.add(btn_AboutUs);
        btn_AboutUs.setBounds(890, 60, 240, 60);

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("<<BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(30, 500, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/Stark Visitor.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Leaving Page...");
       Stark_Industries_Online gy = new Stark_Industries_Online();
        gy.setVisible(true);
        Close();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_HardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HardwareActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Redirecting to Hardware Page...");
        Stark_Industries_Hardware hd = new Stark_Industries_Hardware();
        hd.setVisible(true);
        Close();
    }//GEN-LAST:event_btn_HardwareActionPerformed

    private void btn_SoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SoftwareActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Redirecting to Software Page...");
        Stark_Industries_Software sf = new Stark_Industries_Software();
        sf.setVisible(true);
        Close();
        
    }//GEN-LAST:event_btn_SoftwareActionPerformed

    private void btn_AccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccessoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AccessoriesActionPerformed
public void Close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stark_Industries_Visitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AboutUs;
    private javax.swing.JButton btn_Accessories;
    private javax.swing.JButton btn_Hardware;
    private javax.swing.JButton btn_Software;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
