/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stark.industries;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;


/**
 *
 * @author DarkGamerX100
 */
public class Stark_Industries_Hardware extends javax.swing.JFrame {

    /**
     * Creates new form Stark_Industries_Hardware
     */
    public Stark_Industries_Hardware() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_Blade = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_add2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btn_add3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btn_add4 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("www.starkindustries.org/hardware");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/laptop 1.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-130, 10, 510, 270);

        Stark_Blade_Pro_7.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        Stark_Blade_Pro_7.setForeground(new java.awt.Color(204, 204, 204));
        Stark_Blade_Pro_7.setText("Stark BLADE Pro 7");
        jPanel1.add(Stark_Blade_Pro_7);
        Stark_Blade_Pro_7.setBounds(60, 300, 210, 60);

        jLabel5.setBackground(new java.awt.Color(102, 255, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("PROCESSOR : Intel Core i7 2.50 GHz 7th gen");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 20, 410, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 0));
        jLabel6.setText("RAM : 16GB");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 80, 310, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("STORAGE : 1 TB HDD + 256 GB SSD");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 130, 330, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jLabel8.setText("Operating System : starkOS v2.0");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(400, 180, 310, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("PRICE: 4299.99 AED");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(390, 220, 300, 60);

        btn_Blade.setBackground(new java.awt.Color(51, 51, 51));
        btn_Blade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Blade.setForeground(new java.awt.Color(204, 204, 0));
        btn_Blade.setText("ADD TO CART");
        btn_Blade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Blade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BladeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Blade);
        btn_Blade.setBounds(630, 240, 170, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/Laptop 2.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(980, 40, 320, 220);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setText("PROCESSOR: AMD Ryzen X 2.00 GHz");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1340, 40, 360, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setText("RAM: 8GB");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(1340, 90, 240, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 0));
        jLabel11.setText("STORAGE: 1TB HDD");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1340, 140, 210, 16);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 204, 0));
        jLabel12.setText("Operating System : starkOS v2.0");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1340, 180, 300, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("PRICE : 1099.99 AED");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1340, 230, 250, 29);

        btn_add2.setBackground(new java.awt.Color(51, 51, 51));
        btn_add2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add2.setForeground(new java.awt.Color(204, 204, 0));
        btn_add2.setText("ADD TO CART");
        btn_add2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add2);
        btn_add2.setBounds(1600, 230, 190, 27);

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Stark GALAXYBOOK 5");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1010, 300, 280, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/Desktop 22.jpg"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 440, 310, 310);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 204, 0));
        jLabel16.setText("PROCESSOR: Intel Core i9 4.00 Ghz Overclocked Octacore");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(390, 510, 560, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 204, 0));
        jLabel17.setText("RAM: 32GB");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(390, 560, 400, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 204, 0));
        jLabel18.setText("STORAGE: 2 x 1TB HDD + 500GB SSD");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(390, 600, 530, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 0));
        jLabel19.setText("Operating System: startOS v2.0");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(390, 650, 290, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("PRICE: 10099.99 AED");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(390, 700, 260, 30);

        btn_add3.setBackground(new java.awt.Color(51, 51, 51));
        btn_add3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add3.setForeground(new java.awt.Color(204, 204, 0));
        btn_add3.setText("ADD TO CART");
        btn_add3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add3);
        btn_add3.setBounds(650, 700, 180, 31);

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Stark CYBERPOWERX 510D");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(70, 800, 390, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/Desktop 1.jpg"))); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(1000, 430, 300, 360);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 204, 0));
        jLabel23.setText("PROCESSOR: Intel Xeon 7.00 GHz Octacore");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(1350, 500, 410, 40);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 204, 0));
        jLabel24.setText("RAM: 32GB");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(1350, 550, 390, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 204, 0));
        jLabel25.setText("STORAGE: 2TB HDD + 660GB SSD");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(1350, 600, 340, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 204, 0));
        jLabel26.setText("Operating System: starkOS v2.0");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(1350, 650, 330, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 51));
        jLabel27.setText("PRICE 12999.99 AED");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(1350, 700, 260, 30);

        btn_add4.setBackground(new java.awt.Color(51, 51, 51));
        btn_add4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add4.setForeground(new java.awt.Color(204, 204, 0));
        btn_add4.setText("ADD TO CART");
        btn_add4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add4);
        btn_add4.setBounds(1610, 700, 200, 30);

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("Stark LEGION 52X");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(1030, 780, 260, 40);

        btn_Back.setBackground(new java.awt.Color(102, 102, 102));
        btn_Back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Back.setForeground(new java.awt.Color(255, 51, 0));
        btn_Back.setText("<<BACK");
        btn_Back.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Back);
        btn_Back.setBounds(90, 900, 180, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/Hard Background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1990, 990);

        jTabbedPane1.addTab("Computers", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add3ActionPerformed
        // TODO add your handling code here:
       
        Stark_Industries_PURCHASE obj = new Stark_Industries_PURCHASE();
        Stark_Industries_PURCHASE.txt_ProID.setText("P3");
        Stark_Industries_PURCHASE.txtProName.setText("Stark CyberPowerX 510D");
        obj.setVisible(true);
        Close();
    }//GEN-LAST:event_btn_add3ActionPerformed

    private void btn_add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add2ActionPerformed
        // TODO add your handling code here:
        Stark_Industries_PURCHASE obj = new Stark_Industries_PURCHASE();
        Stark_Industries_PURCHASE.txt_ProID.setText("P2");
        Stark_Industries_PURCHASE.txtProName.setText("Stark Galaxy Book 5");
        obj.setVisible(true);
        Close();
    }//GEN-LAST:event_btn_add2ActionPerformed

    private void btn_BladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BladeActionPerformed
        // TODO add your handling code here:

        Stark_Industries_PURCHASE obj = new Stark_Industries_PURCHASE();
        Stark_Industries_PURCHASE.txt_ProID.setText("P1");
        Stark_Industries_PURCHASE.txtProName.setText("Stark Blade Pro 7");
        obj.setVisible(true);
        Close();
    }//GEN-LAST:event_btn_BladeActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Leaving Page...");
        Stark_Industries_Visitor gy = new Stark_Industries_Visitor();
        gy.setVisible(true);
        Close();
        
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add4ActionPerformed
        // TODO add your handling code here:
        Stark_Industries_PURCHASE obj = new Stark_Industries_PURCHASE();
        Stark_Industries_PURCHASE.txt_ProID.setText("P4");
        Stark_Industries_PURCHASE.txtProName.setText("Stark LEGION 52X");
        obj.setVisible(true);
        Close();
        
    }//GEN-LAST:event_btn_add4ActionPerformed
 public void Close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Hardware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stark_Industries_Hardware().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final transient javax.swing.JLabel Stark_Blade_Pro_7 = new javax.swing.JLabel();
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Blade;
    private javax.swing.JButton btn_add2;
    private javax.swing.JButton btn_add3;
    private javax.swing.JButton btn_add4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
