/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stark.industries;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.JOptionPane;

/**
 *
 * @author DarkGamerX100
 */
public class Stark_Industries_Online extends javax.swing.JFrame {

    /**
     * Creates new form Stark_Industries_Online
     */
    public Stark_Industries_Online() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_ADMIN = new javax.swing.JButton();
        btn_WEB = new javax.swing.JButton();
        btn_LOGGOUT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("STARK INDUSTRIES");

        jPanel1.setLayout(null);

        btn_ADMIN.setBackground(new java.awt.Color(102, 102, 0));
        btn_ADMIN.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        btn_ADMIN.setText("ADMINISTRATOR");
        btn_ADMIN.setBorder(null);
        btn_ADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ADMINActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ADMIN);
        btn_ADMIN.setBounds(110, 550, 340, 80);

        btn_WEB.setBackground(new java.awt.Color(102, 102, 0));
        btn_WEB.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        btn_WEB.setText("WEB PAGE");
        btn_WEB.setBorder(null);
        btn_WEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WEBActionPerformed(evt);
            }
        });
        jPanel1.add(btn_WEB);
        btn_WEB.setBounds(790, 550, 340, 80);

        btn_LOGGOUT.setBackground(new java.awt.Color(204, 0, 51));
        btn_LOGGOUT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_LOGGOUT.setForeground(new java.awt.Color(51, 51, 51));
        btn_LOGGOUT.setText("LOG OUT");
        btn_LOGGOUT.setBorder(null);
        btn_LOGGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LOGGOUTActionPerformed(evt);
            }
        });
        jPanel1.add(btn_LOGGOUT);
        btn_LOGGOUT.setBounds(490, 690, 190, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/ws_Stark_Industries_1280x1024.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1210, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ADMINActionPerformed
        // TODO add your handling code here:
        try{
            JFXPanel j = new JFXPanel();
            String uri = new File("Admin Welcome.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
        Stark_Industries_ADMIN ad = new Stark_Industries_ADMIN();
        ad.setVisible(true);
        Close();
        
        
    }//GEN-LAST:event_btn_ADMINActionPerformed

    private void btn_WEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WEBActionPerformed
        // TODO add your handling code here:
        try{
                JFXPanel j = new JFXPanel();
                String uri = new File("Welcome_Cust.mp3").toURI().toString();
                new MediaPlayer(new Media(uri)).play();
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        
        Stark_Industries_Visitor vi = new Stark_Industries_Visitor();
        vi.setVisible(true);
        Close();
    }//GEN-LAST:event_btn_WEBActionPerformed

    private void btn_LOGGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LOGGOUTActionPerformed
        // TODO add your handling code here
        JOptionPane.showMessageDialog(null, "LOGGING OUT...");
        Stark_Industries_HOME home = new Stark_Industries_HOME();
        home.setVisible(true);
        Close();
    }//GEN-LAST:event_btn_LOGGOUTActionPerformed

      public void Close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Online.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Online.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Online.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Online.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stark_Industries_Online().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ADMIN;
    private javax.swing.JButton btn_LOGGOUT;
    private javax.swing.JButton btn_WEB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
