/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stark.industries;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author DarkGamerX100
 */
public class Stark_Industries_TERMINATE extends javax.swing.JFrame {

    /**
     * Creates new form Stark_Industries_TERMINATE
     */
    public Stark_Industries_TERMINATE() {
        initComponents();
        btn_Terminate.setVisible(false);
        btn_Clear.setVisible(false);
        lA.setVisible(false);
        lC.setVisible(false);
        lD.setVisible(false);
        lG.setVisible(false);
        lN.setVisible(false);
        lS.setVisible(false);
        lC.setVisible(false);
        tname.setVisible(false);
        txtGen.setVisible(false);
        tDept.setVisible(false);
        tSal.setVisible(false);
        tAdd.setVisible(false);
        tCon.setVisible(false);
        employer_icon.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lN = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        txtGen = new javax.swing.JTextField();
        lG = new javax.swing.JLabel();
        lD = new javax.swing.JLabel();
        tDept = new javax.swing.JTextField();
        tSal = new javax.swing.JTextField();
        lS = new javax.swing.JLabel();
        lA = new javax.swing.JLabel();
        tAdd = new javax.swing.JTextField();
        tCon = new javax.swing.JTextField();
        lC = new javax.swing.JLabel();
        btn_Check = new javax.swing.JButton();
        btn_Return = new javax.swing.JButton();
        employer_icon = new javax.swing.JLabel();
        btn_Terminate = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TERMINATE WINDOW");

        jPanel1.setLayout(null);

        txtID.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtID.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(txtID);
        txtID.setBounds(280, 30, 360, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 50, 150, 30);

        lN.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lN.setForeground(new java.awt.Color(153, 0, 153));
        lN.setText("NAME");
        jPanel1.add(lN);
        lN.setBounds(30, 140, 100, 30);

        tname.setEditable(false);
        tname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tname.setForeground(new java.awt.Color(255, 51, 102));
        jPanel1.add(tname);
        tname.setBounds(280, 130, 360, 50);

        txtGen.setEditable(false);
        txtGen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtGen.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(txtGen);
        txtGen.setBounds(280, 230, 360, 50);

        lG.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lG.setForeground(new java.awt.Color(153, 0, 153));
        lG.setText("GENDER");
        jPanel1.add(lG);
        lG.setBounds(30, 230, 180, 50);

        lD.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lD.setForeground(new java.awt.Color(153, 0, 153));
        lD.setText("DEPARMENT");
        jPanel1.add(lD);
        lD.setBounds(30, 330, 210, 30);

        tDept.setEditable(false);
        tDept.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tDept.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(tDept);
        tDept.setBounds(280, 320, 360, 50);

        tSal.setEditable(false);
        tSal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tSal.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(tSal);
        tSal.setBounds(280, 410, 360, 50);

        lS.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lS.setForeground(new java.awt.Color(153, 0, 153));
        lS.setText("SALARY");
        jPanel1.add(lS);
        lS.setBounds(30, 420, 180, 30);

        lA.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lA.setForeground(new java.awt.Color(153, 0, 153));
        lA.setText("ADDRESS");
        jPanel1.add(lA);
        lA.setBounds(30, 510, 180, 30);

        tAdd.setEditable(false);
        tAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tAdd.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(tAdd);
        tAdd.setBounds(280, 500, 360, 50);

        tCon.setEditable(false);
        tCon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tCon.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(tCon);
        tCon.setBounds(280, 590, 360, 50);

        lC.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lC.setForeground(new java.awt.Color(153, 0, 153));
        lC.setText("CONTACT");
        jPanel1.add(lC);
        lC.setBounds(30, 600, 200, 30);

        btn_Check.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Check.setForeground(new java.awt.Color(255, 0, 0));
        btn_Check.setText("CHECK ID");
        btn_Check.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Check);
        btn_Check.setBounds(670, 30, 190, 50);

        btn_Return.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Return.setForeground(new java.awt.Color(255, 102, 102));
        btn_Return.setText("RETURN");
        btn_Return.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btn_Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Return);
        btn_Return.setBounds(1160, 700, 150, 50);

        employer_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/employer.jpg"))); // NOI18N
        jPanel1.add(employer_icon);
        employer_icon.setBounds(1020, 40, 300, 300);

        btn_Terminate.setBackground(new java.awt.Color(255, 255, 255));
        btn_Terminate.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btn_Terminate.setForeground(new java.awt.Color(255, 51, 0));
        btn_Terminate.setText("TERMINATE");
        btn_Terminate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TerminateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Terminate);
        btn_Terminate.setBounds(570, 700, 250, 50);

        btn_Clear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Clear.setForeground(new java.awt.Color(0, 153, 51));
        btn_Clear.setText("CLEAR");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Clear);
        btn_Clear.setBounds(1160, 620, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/Details.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Statement stmt = null;
     ResultSet rs = null;
     
     
     
     public static Connection getConnection(){
         Connection con=null;
         try{
             Class.forName("com.mysql.jdbc.Driver");
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stark_industries","root","stid");
         }
         catch (Exception ex){
             JOptionPane.showMessageDialog(null, "Stark Server Connection Failure");
         }
         
         return con;
     }
    private void btn_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckActionPerformed
        // TODO add your handling code here:
        btn_Terminate.setVisible(true);
        btn_Clear.setVisible(true);
        lA.setVisible(true);
        lC.setVisible(true);
        lD.setVisible(true);
        lG.setVisible(true);
        lN.setVisible(true);
        lS.setVisible(true);
        lC.setVisible(true);
        tname.setVisible(true);
        txtGen.setVisible(true);
        tDept.setVisible(true);
        tSal.setVisible(true);
        tAdd.setVisible(true);
        tCon.setVisible(true);

        String un=txtID.getText();
        PreparedStatement pstmt = null;
        Connection conn=null;
        ResultSet rs = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/stark_industries","root","stid");
            pstmt=conn.prepareStatement("select * from employer where ID=?");
            pstmt.setString(1, un);
            rs=pstmt.executeQuery();

            while(rs.next()){
                tname.setText(rs.getString("Name"));
                tDept.setText(rs.getString("Department"));
                tSal.setText(rs.getString("Salary"));
                tAdd.setText(rs.getString("Address"));
                tCon.setText(rs.getString("Contact"));
                txtGen.setText(rs.getString("Gender"));

                employer_icon.setVisible(true);

            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        finally{
            try{
                conn.close();
                pstmt.close();
                rs.close();
            }
            catch(Exception ex){

            }

        }

    }//GEN-LAST:event_btn_CheckActionPerformed

    private void btn_ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReturnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Exiting Terminate Window...");
        Stark_Industries_ADMIN gy = new Stark_Industries_ADMIN();
        gy.setVisible(true);
        close();

    }//GEN-LAST:event_btn_ReturnActionPerformed

    private void btn_TerminateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TerminateActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null,"'Are You Sure To TERMINATE The Employer  "+tname.getText()+"","TERMINATE",JOptionPane.YES_NO_OPTION);
        if(p==0){
        try{
            Connection con= getConnection();
            stmt=con.createStatement();
            String id = txtID.getText();
            String command="delete from Employer where id='"+id+"';";
            stmt.executeUpdate(command);
            JOptionPane.showMessageDialog(null, "Employer Terminated");
            stmt.close();
            con.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
       
       
        
        }   
    }//GEN-LAST:event_btn_TerminateActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        tname.setText("");
        txtGen.setText("");
        tDept.setText("");
        tSal.setText("");
        tAdd.setText("");
        tCon.setText("");
    }//GEN-LAST:event_btn_ClearActionPerformed

    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_TERMINATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_TERMINATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_TERMINATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_TERMINATE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stark_Industries_TERMINATE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Check;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Return;
    private javax.swing.JButton btn_Terminate;
    private javax.swing.JLabel employer_icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lA;
    private javax.swing.JLabel lC;
    private javax.swing.JLabel lD;
    private javax.swing.JLabel lG;
    private javax.swing.JLabel lN;
    private javax.swing.JLabel lS;
    public static javax.swing.JTextField tAdd;
    public static javax.swing.JTextField tCon;
    public static javax.swing.JTextField tDept;
    public static javax.swing.JTextField tSal;
    public static transient volatile javax.swing.JTextField tname;
    private javax.swing.JTextField txtGen;
    public static transient volatile javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
