/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stark.industries;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author DarkGamerX100
 */
public class Stark_Industries_Software extends javax.swing.JFrame {

    /**
     * Creates new form Stark_Industries_Software
     */
    public Stark_Industries_Software() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_add1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_add2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btn_add3 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btn_add4 = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("www.starkindusries.com/software");

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/antivirus.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 270, 260);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Stark DEFENDER 2018 [Anti-Vitus]");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 300, 390, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setText("File Protection");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 50, 210, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("In-depth System Scanning");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 20, 360, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 0));
        jLabel6.setText("Web Protection");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 90, 230, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("Safe Web Surfing");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 130, 200, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jLabel8.setText("2 Years License");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(280, 160, 200, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("PRICE : 199.99 AED");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 220, 240, 30);

        btn_add1.setBackground(new java.awt.Color(52, 52, 52));
        btn_add1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add1.setForeground(new java.awt.Color(204, 204, 0));
        btn_add1.setText("ADD TO CART");
        btn_add1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add1);
        btn_add1.setBounds(510, 220, 180, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/music player.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(900, 20, 340, 300);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Stark VIBE X [Music Player]");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(940, 340, 320, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 204, 0));
        jLabel12.setText("Supports all Audio Formats");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1270, 50, 270, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 204, 0));
        jLabel13.setText("Attracive Interface");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(1270, 100, 240, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 0));
        jLabel14.setText("Lifetime License");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1270, 200, 250, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 0));
        jLabel15.setText("Advanced EQ Settings");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(1270, 140, 210, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("PRICE : 10.99 AED");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(1270, 260, 220, 30);

        btn_add2.setBackground(new java.awt.Color(52, 52, 52));
        btn_add2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add2.setForeground(new java.awt.Color(204, 204, 0));
        btn_add2.setText("ADD TO CART");
        btn_add2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add2);
        btn_add2.setBounds(1540, 260, 170, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/video edit.jpg"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 480, 360, 300);

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Stark OPENSHOT [Professional Video Editor]");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(40, 790, 560, 60);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 0));
        jLabel19.setText("Streamline graphics creation with Master Properties");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(410, 500, 480, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 204, 0));
        jLabel20.setText("Data-driven animation");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(410, 540, 250, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 204, 0));
        jLabel21.setText("Open Motion Graphics templates");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(410, 580, 450, 40);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 204, 0));
        jLabel22.setText("Essential Graphics Panel");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(410, 630, 400, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 204, 0));
        jLabel23.setText("Lifetime License");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(410, 670, 320, 40);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 51));
        jLabel24.setText("PRICE : 299.99 AED ");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(410, 730, 220, 40);

        btn_add3.setBackground(new java.awt.Color(52, 52, 52));
        btn_add3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add3.setForeground(new java.awt.Color(204, 204, 0));
        btn_add3.setText("ADD TO CART");
        btn_add3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add3);
        btn_add3.setBounds(650, 740, 170, 25);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/photo editor.png"))); // NOI18N
        jPanel1.add(jLabel25);
        jLabel25.setBounds(990, 480, 260, 270);

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Stark ATOM [Professional Photo Editor]");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(960, 790, 460, 40);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 204, 0));
        jLabel27.setText("Stroke Smoothing");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(1330, 510, 280, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 204, 0));
        jLabel28.setText("Color and Luminance Range Masking");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(1330, 550, 370, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 204, 0));
        jLabel29.setText("Access Lightroom Photos");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(1330, 590, 350, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 204, 0));
        jLabel30.setText("360 Panorama Workflow");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(1330, 630, 330, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 204, 0));
        jLabel31.setText("Lifetime License");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(1330, 670, 280, 30);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 51));
        jLabel32.setText("PRICE : 299.99 AED");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(1330, 730, 230, 30);

        btn_add4.setBackground(new java.awt.Color(52, 52, 52));
        btn_add4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_add4.setForeground(new java.awt.Color(204, 204, 0));
        btn_add4.setText("ADD TO CART");
        btn_add4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add4);
        btn_add4.setBounds(1560, 730, 170, 27);

        btn_Back.setBackground(new java.awt.Color(102, 102, 102));
        btn_Back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Back.setForeground(new java.awt.Color(255, 51, 0));
        btn_Back.setText("<<BACK");
        btn_Back.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Back);
        btn_Back.setBounds(60, 900, 180, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/Hard Background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-170, -80, 1920, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
        // TODO add your handling code here:
        Stark_Industries_PURCHASE obj = new Stark_Industries_PURCHASE();
        Stark_Industries_PURCHASE.txt_ProID.setText("P5");
        Stark_Industries_PURCHASE.txtProName.setText("Stark Defender 2018");
        obj.setVisible(true);
        Close();
    }//GEN-LAST:event_btn_add1ActionPerformed

    private void btn_add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add2ActionPerformed
        // TODO add your handling code here:
        Stark_Industries_PURCHASE obj = new Stark_Industries_PURCHASE();
        Stark_Industries_PURCHASE.txt_ProID.setText("P6");
        Stark_Industries_PURCHASE.txtProName.setText("Stark Vibe X");
        obj.setVisible(true);
        Close();
        
        
    }//GEN-LAST:event_btn_add2ActionPerformed

    private void btn_add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add3ActionPerformed
        // TODO add your handling code here:
        
        Stark_Industries_PURCHASE obj = new Stark_Industries_PURCHASE();
        Stark_Industries_PURCHASE.txt_ProID.setText("P7");
        Stark_Industries_PURCHASE.txtProName.setText("Stark Openshot");
        obj.setVisible(true);
        Close();
        
    }//GEN-LAST:event_btn_add3ActionPerformed

    private void btn_add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add4ActionPerformed
        // TODO add your handling code here:
        Stark_Industries_PURCHASE obj = new Stark_Industries_PURCHASE();
        Stark_Industries_PURCHASE.txt_ProID.setText("P8");
        Stark_Industries_PURCHASE.txtProName.setText("Stark ATOM");
        obj.setVisible(true);
        Close();
        
    }//GEN-LAST:event_btn_add4ActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Leaving Page...");
        Stark_Industries_Visitor gy = new Stark_Industries_Visitor();
        gy.setVisible(true);
        Close();

    }//GEN-LAST:event_btn_BackActionPerformed

    public void Close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_Software.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stark_Industries_Software().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_add1;
    private javax.swing.JButton btn_add2;
    private javax.swing.JButton btn_add3;
    private javax.swing.JButton btn_add4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
